---
title: Curriculum Vitae
subtitle: Gertrud K. Nürnberg
toc: true
---

Freshwater Research  
3421 Hwy 117, R.R. #1  
Baysville, ON   
P0B 1A0  Canada  
	
{{< fa phone >}} Phone: (705) 767-3718    
{{< fa envelope >}} Email: <gkn@fwr.ca>   
{{< fa globe >}} Website: <http://www.fwr.ca>

{{< fa brands researchgate >}} ResearchGate: <http://www.researchgate.net/profile/Gertrud_Nurnberg>  
{{< fa brands orcid >}} ORCID: <http://orcid.org/0000-0003-1752-6562>

__Citizenship:__ German, Canadian  
__Languages:__ English, German, French  
__Important values:__ Environment, Human rights, Poverty alleviation

## Degrees

- Ph.D. Biology with "Honours" (1984), McGill University, Montreal, Quebec: [Availability of phosphorus from anoxic hypolimnia to epilimnetic plankton](http://digitool.Library.McGill.CA:80/R/-?func=dbin-jump-full&object_id=71914&silo_library=GEN01)
- Diplom (M.Sc.) Biology (1977), University of Frankfurt, Germany
- Vordiplom (B.Sc.) Biology (1974), University of Cologne, Germany

## Employment

- __1984-Present__ Head of company: Freshwater Research.  
- __1984-1992__ Research Associate at York University.  

## Community Outreach and Involvement

- __2000-Present__ Water quality specialist and Lake Partner (MOECC) for the "Grandview Lake Association"
- __2011-Present__ Advisory board of the "Central Algoma Freshwater Coalition"

## Teaching

### Workshops (Presented)
__April 2010__ Lakes & Algal Blooms – Facts, Fiction & Fixes, Thessalon, Algoma (East Algoma Stewardship Council)

__2003-Present__ Workshops at the annual North American Lake Management Symposia
  - Internal Phosphorus Loading and Cyanobacteria
  - Internal phosphorus loading I: its effect on lake water quality, its determination, quantification and prediction, and remediation options
  - Internal phosphorus loading II: Hands-on applications of the theoretical concepts and models presented in Internal phosphorus loading I.

### Mentoring

__2015__ Principal supervisor for an Integrated Water Resources Management Internship of a Master student at Department of Bioresource Engineering, McGill University, Montreal, Quebec.

__2010__ Joint supervisor for Master student at Université Laval, Québec City, Québec.

### Formal Teaching

__1979-80__ Teaching Assistant at McGill University: Ecology, field and laboratory courses.

__1978-79__ Supply Teacher at Highschool in Frankfurt, Germany: Grade 12 Biology

__1975-77__ Teaching Assistant at the University of Frankfurt: Introductory and graduate courses in general biology, zoology and ecology.


## Scientific Society memberships

- North American Lake Management Society (NALMS)  
  - __1999-2002__ Regional Director for Region XI, Eastern Canada
  - Member of the NALMS 1995 Symposium in Toronto organizing committee
-  Society of Canadian Aquatic Sciences (SCAS) [former Society of Canadian Limnologists]
- Canadian Society of Environmental Biologists (CSEB)

## Editing and reviewing responsibilities

- __1996-2014__ Associate Editor for the Journal of Lake and Reservoir Management  
- Numerous reviews for many scientific journals.  
- Numerous critical evaluations of grant proposals in Canada, the USA, Great Britain, Czech Republic, Estonia.  
- External examiner for PhD thesis: University of Southern Denmark; University of Granada, Spain

## Fellowships & Awards

- __2018__ North American Lake Management (NALMS) Secchi Disk Award 2018, "for outstanding service to the NALMS Society."
- __2017__ Publons Peer Review Awards 2017, "as one of the top 1 per cent of peer reviewer in Environmental Science."
- __2012__ Outstanding Reviewer Citation for the journal Limnology and Oceanography of the Association for the Sciences of Limnology and Oceanography (ASLO), Bulletin Vol 21 (2), May 2012
- __2004__ Best Journal Article Award for NALMS’ Journal of Lake and Reservoir Management (Nürnberg et al. 2003: 19, pages 307-322). North American Lake Management Society.
- __2003__ Technical excellence award for outstanding research in lake restoration, protection and management, North American Lake Management Society.
- __1992__ Foreign Speaker Travel Award for NALMS conference in Columbia, Ohio, USA.
- __1986-1988__ Postdoctoral Fellow, Natural Sciences and Engineering Research Council of Canada, York University, Downsview, Toronto.
- __1984-1985__ Research Fellow, Trent University, Peterborough Ontario.
- __1984-1986__ Jessie Smith Noyes Foundation Fellowship, Lake Waramaug, Connecticut, USA.
- __1982__ Travel Award McGill University for ASLO conference in North Carolina, USA.
- __1983__ Travel Award McGill University for SIL conference in Lyon, France.
- __1979-1983__ Ph.D. Scholarship, Social Sciences and Humanities Research Council of Canada.

## Grants

#### _Environment and Climate Change Canada_, _Canadian Department of Fisheries and Oceans_ and _Environment Canada_

__2016-2017__ “Internal phosphorus (P) load assessment in Georgian Bay embayments to improve understanding about P sources and onshore-offshore productivity gradients” for the Freshwater Program of  (ECCC) - Lake Simcoe, Eastern Georgian Bay.

__2013-2014__ “Quantification of the internal phosphorus load in Lake Winnipeg to improve phosphorus budgets” for the Lake Winnipeg Basin Stewardship Fund (LWBSF).

__2010-2012__ “Quantification of the internal phosphorus load in Lake Simcoe to improve phosphorus budgets” with Prof Lew Molot, York University for the Lake Simcoe Clean-Up Fund.

__2002-2006__ Contribution of point and diffuse loads to the nutrient budget of Canadian Rivers: The Athabaska River - Joint project with the Leipzig Institute of Freshwater Ecology and Inland Fisheries, Berlin, Germany for the application of the MONERIS Model.

__1996__ Productivity in brownwater lakes.

__1994__ Analysis of nutrient dynamics and productivity data in clear versus brownwater lakes.

__1993__ Review of phosphorus dynamics and primary productivity in dystrophic bog lakes.


#### _Ontario Ministry of Environment and Climate Change_
__2014-2015__ "Analysis of Upwelling and Onshore Circulation of Low Oxygen Water on the Coastal Ecology of the North Shore of Lake Erie's Central Basin" as a cooperative research project.

__1992__ "Continuation of the study of the anoxic factor of lakes and its prediction" as a cooperative research project.

__1990-1991__ "A study of the anoxic factor of lakes and its prediction" as a cooperative research project.

__1989-1990__ "Study of iron cycles in lakes using whole lake mass balances" as a cooperative research project.

__1987__ Consulting on the sediment phosphorus release in Rice and Sturgeon Lakes.

__1986__ Assessment of eutrophication in Gravenhurst Bay (calculation of phosphorus budget),

__1985__ Determination of sediment water interactions in Gravenhurst Bay (experimental), as a cooperative research project.

## Invited talks, workshop participation

(see Presented Papers below for complete list and details)

### Talks
- Lake Winnipeg Research Council (LWRC), Winnipeg, MB Canada
- Lake Simcoe Environmental Management Strategy, Barrie, O, Canada
- University of Alberta, Edmonton, AB Canada
- University of Toronto, Scarborough Campus, ON Canada
- York University, Downsview, Toronto, ON Canada
- Canadian Centre for Inland Waters, Burlington, ON Canada
- Alberta Ministry of the Environment, Edmonton, AB Canada
- Ontario Ministry of the Environment, Dorset, ON Canada
- Queens University, Kingston, ON Canada
- Annis Water Resources Institute of Grand Valley State University, MI USA
- Michigan Technological University, Houghton, MI USA
- University of Washington, Seattle, WA USA
- Lahti Lakes 2018, Lahti, Finland
- Alberta Lake Management Society
- University of Minnesota, Ecology, Evolution & Behavior Seminar Series

### Workshops (Participant)
- Science synthesis workshop of the International Joint Commission’s Lake Erie Ecosystem Priority (LEEP), February 2013, Windsor, Ontario. 
- Workshop on "Nutrient cycling/food web interactions for Lake Ontario", State Univ. of N.Y., Buffalo, NY USA.
- CARE Project incl. 2 Workshops, Lake Pyhäjärvi, Kauttua, Finland
- Baltic Sea 2020 Workshop, Björn Carlson Foundation for the Baltic Sea, Lund, Sweden.
- Umweltforschungszentrum Leipzig-Halle, Sektion Gew&#228;sserforschung Magdeburg, Germany
- Leipzig Institute of Freshwater Ecology and Inland Fisheries, Neuglobsoe, Germany

## Publications

Tammeorg, O., Nürnberg, G., Tõnno, I., Kisand, A., Tuvikene, L., Nõges, T., Nõges, P., 2022a. Sediment phosphorus mobility in Võrtsjärv, a large shallow lake: Insights from phosphorus sorption experiments and long-term monitoring. Science of The Total Environment 154572.

Tammeorg, O., Nürnberg, G.K., Nõges, P., Niemistö, J., 2022b. The role of humic substances in sediment phosphorus release in northern lakes. Science of The Total Environment 833, 155257. https://doi.org/10.1016/j.scitotenv.2022.155257

Tammeorg, O., Nürnberg, G., Horppila, J., Haldna, M., Niemistö, J., 2020a. Redox-related release of phosphorus from sediments in large and shallow Lake Peipsi: Evidence from sediment studies and long-term monitoring data. Journal of Great Lakes Research 46, 1595-1603. https://doi.org/10.1016/j.jglr.2020.08.023

Tammeorg, O., Nürnberg, G., Niemistö, J., Haldna, M., Horppila, J., 2020b. Internal phosphorus loading due to sediment anoxia in shallow areas: implications for lake aeration treatments. Aquatic Sciences 82. https://doi.org/10.1007/s00027-020-00724-0

Ventelä, A.-M., Ekholm, P., Kirkkala, T., Lehtoranta, J., Nürnberg, G.K., Tarvainen, M., Sarvala, J., 2020. A review of internal phosphorus loading evidence in Säkylän Pyhäjärvi, Finland. In 'A.D. Steinman and B.M. Spears (Eds.), Internal Phosphorus Loading:  Causes, Case Studies, and Management' 'Chapter 18'. J. Ross Publishing, Plantation, FL, pp. 345-357.

__Nürnberg, G.K.__ 2020. Internal phosphorus loading models: A critical review. In: A.D. Steinman and B.M. Spears (Eds.), Internal Phosphorus Loading:  Causes, case studies, and management. Plantation, FL: J. Ross Publishing. p. 45-62.

--. 2020. Observed and modelled internal phosphorus loads in stratified and polymictic basins of a mesotrophic lake. In: A.D. Steinman and B.M. Spears (Eds.), Internal Phosphorus Loading:  Causes, case studies, and management. Plantation, FL: J. Ross Publishing. p. 111-123.

--. 2019. Quantification of Anoxia and Hypoxia in Water Bodies (2). In: Water Encyclopedia. John Wiley & Sons, Inc. DOI  10.1002/9781119300762.wsts0081

--. 2019. Hypolimnetic withdrawal as a lake restoration technique: Determination of feasibility and continued benefits. Hydrobiologia 00:000-000

__Nürnberg, G.K.__ T. Howell, M. Palmer. 2019. 28 years of impact from Central Basin hypoxia and internal phosphorus loading on north shore water quality in Lake Erie. Inland Waters 9: 362-373. doi.org/10.1080/20442041.2019.1568072

__Nürnberg, G.K.__ R. Fischer, A. Paterson. 2018. Reduced phosphorus retention by anoxic bottom sediments after the remediation of an industrial acidified lake area: Indications from P, Al, and Fe sediment fractions. Science of the Total Environment 626: 412–422.

__Nürnberg, G.K.__ 2017. Attempted management of cyanobacteria by Phoslock (lanthanum-modified clay) in Canadian lakes, water quality results and predictions. Lake and Reservoir Management 33, 163-170. DOI: 10.1080/10402381.2016.1265618

__Nürnberg, G.K.__ and B.D. LaZerte. 2016. Trophic state decrease after lanthanum-modified bentonite (Phoslock) application to a hyper-eutrophic polymictic urban lake frequented by Canada geese (_Branta canadensis_). Lake and Reservoir Management 32, 74-88. DOI: 10.1080/10402381.2015.1133739

--. 2016. More than 20 years of estimated internal phosphorus loading in polymictic, eutrophic Lake Winnipeg, Manitoba. J. Great Lakes Res. 42, 18-27. DOI: 10.1016/j.jglr.2015.11.003

Spears, B.M., E.B. Mackay, S. Yasseri, I.D.M. Gunn, K.E. Waters, C. Andrews, S. Cole, M. de Ville, A. Kelly, S. Meis, A.L. Moore, __G.K. Nürnberg__, F. van Oosterhout, J.-A. Pitt, G. Madgwick, H.J. Woods and M. Lürling. 2016. A meta-analysis of water quality and aquatic macrophyte responses in 18 lakes treated with lanthanum modified bentonite (PHOSLOCK®). Water Research. DOI: 10.1016/j.watres.2015.08.020

__Nürnberg, G.K.__, B.D. LaZerte, P.S. Loh, L.A. Molot. 2013. Quantification of internal phosphorus load in large, partially polymictic and mesotrophic Lake Simcoe, Ontario. J Great Lakes Res 39, 271-279.

__Nürnberg, G.K.__, L.A. Molot, E. O’Connor, H. Jarjanazi, J.G. Winter and J.D. Young. 2013. Evidence for internal phosphorus loading, hypoxia and effects on phytoplankton in partially polymictic Lake Simcoe, Ontario. J Great Lakes Res 39, 259-270.

Loh, P.S., L.A. Molot, __G.K. Nürnberg__, S.B. Watson and B. Ginn. 2013. Evaluating relationships between sediment chemistry and anoxic phosphorus and iron release across three different water bodies. Inland Waters 3, 105-117.

__Nürnberg, G.K.__, M. Tarvainen, A.-M. Ventelä and J. Sarvala. 2012. Internal phosphorus load estimation during biomanipulation in a large polymictic and mesotrophic lake Inland Waters 2, 147-162.

Labrecque V, __G.K. Nürnberg__, R. Tremblay and R. Pienitz. 2012. Caractérisation de la charge interne de phosphore du lac Nairne, Charlevoix, Québec (in French). - Internal phosphorus load assessment of Lake Nairne, Charlevoix, Quebec. Rev. Sci. L'Eau: 25 (1):77-93.

__Nürnberg, G.K.__ 2009. Assessing internal phosphorus load – problems to be solved, Lake and Reservoir Management, 25(4): 419-432.

Conley, D.J., S. Björck, E. Bonsdorff, J. Carstensen, G. Destouni, B.G. Gustafsson, S. Hietanen, M. Kortekaas, H. Kuosa, H.E.M. Meier, B. Müller-Karulis, K. Nordberg, A. Norkko, __G.K. Nürnberg__, H. Pitkänen, N.N. Rabalais, R. Rosenberg, O.P. Savchuk, C.P. Slomp, M. Voss, F. Wulff and L. Zillén. 2009. Critical Review: Hypoxia-related processes in the Baltic Sea. Environ. Sci. Technol. 43: 3412-3420.

Cyr, H., S.K. McCabe and __G.K. Nürnberg__. 2009. Phosphorus sorption experiments and the potential for internal phosphorus loading in littoral areas of a stratified lake. Water Res. 43:1654-1666

__Nürnberg, G.K.__ 2007. Low-Nitrate-Days (LND), a potential indicator of cyanobacteria blooms in a eutrophic hardwater reservoir. Water Quality Research Journal of Canada 42: 269-283.

--. Lake responses to long-term hypolimnetic withdrawal treatments. Lake and Reservoir Management 23: 388-409.

__Nürnberg, G.K.__ 2005. Quantification of internal phosphorus loading in polymictic lakes. Verhandlungen Internationalen Vereinigung Limnologie (SIL) 29: 623-626.

Cyr, H. and __G.K. Nürnberg__. 2005. Methodological biases in phosphate sorption experiments. p. 55-66 in  L. Serrano and H.L. Golterman (editors), Phosphates in Sediments, Proceedings of the 4th International Symposium. Backhuys Publishers, the Netherlands.

__Nürnberg, G.K.__ 2004. Quantified hypoxia and anoxia in lakes and reservoirs. TheScientificWorld 4, 42-54.

--. 2005. Internal phosphorus loading or "the devil is in the sediments". Lake Stewardship Newsletter, 9-10.

__Nürnberg, G.K.__ and B.D. LaZerte. 2004. Modeling the effect of development on internal phosphorus load in nutrient-poor lakes. Water Resources Research 40: W01105. doi:10.1029/2003WR002410

Havens K.E. and __G.K. Nürnberg__. 2004. The Phosphorus-Chlorophyll Relationship in Lakes: Potential Influences of Color and Mixing Regime. Lake and Reservoir Management 20, 000-000.

__Nürnberg, G.K.__ and B.D. LaZerte. 2003/4. Ontario lakes: The importance of lake management. NALMS Lakeline 23 (4): 32-37.

__Nürnberg, G.K.__, B.D. LaZerte and D.D. Olding. 2003. An artificially induced Planktothrix rubescens surface bloom in a small kettle lake in southern Ontario compared to blooms world-wide. Lake and Reservoir Management 19: 307-322.

__Nürnberg, G.K.__ 2002. Probability of winterkill in Central Ontario lakes. Newsletter of the American Fisheries Society Southern Ontario Chapter, Sep 2002: 2-3

--. 2002. Quantification of oxygen depletion in lakes and reservoirs with the hypoxic factor. Lake and Reservoir Management 18, 298-305.

--. 2001. Eutrophication and Trophic State - Why does lake water (quality) differ from lake to lake? NALMS Lakeline 21(1): 29-33.

__Nürnberg, G.K.__ and B.D. LaZerte. 2001. Predicting Water Quality, Chapter 5, p. 139-163 in C. Holdren, B. Jones and J. Taggert (eds.), Managing Lakes and Reservoirs, 3rd ed., North American Lake Management Society, Terrene Inst. and US-EPA, EPA 841-B-01-006.

__Nürnberg, G.K.__ 1999.  Determining trophic state in experimental lakes. - Comment. Limnology and Oceanography 44: 1176-1179.

__Nürnberg, G.K.__ and M. Shaw. 1999. Productivity of clear and humic lakes: nutrients, phytoplankton, bacteria. Hydrobiologia 382: 97-112.

__Nürnberg, G.K.__ 1998. Prediction of annual and seasonal phosphorus concentrations in stratified and polymictic lakes. Limnology and Oceanography 43: 1544-1552.

--. 1997. Coping with water quality problems due to hypolimnetic anoxia in Central Ontario Lakes. Water Quality Research Journal of Canada 32: 391-405.

--. 1996. Trophic state of clear and coloured, soft-and hardwater lakes with special consideration of nutrients, anoxia, phytoplankton and fish. Lake and Reservoir Management 12: 432-447.

--. 1996. Comment: Phosphorus budgets and stoichiometry during the open-water season in two unmanipulated lakes in the Experimental Lakes Area, northwestern Ontario. Canadian J. Fisheries Aquatic Science 53: 1469-1471.

--. 1995. Quantifying anoxia in lakes. Limnology and Oceanography 40: 1100-1111.

--. 1995. Anoxic factor, a quantitative measure of anoxia and fish species richness in Central Ontario lakes. Transactions of the American Fisheries Society 124: 677-686.

--. 1994. Phosphorus release from anoxic sediments: What we know and how we can deal with it. Limnetica 10: 1-4.

__Nürnberg, G.K.__ and P.J. Dillon. 1993. Iron budgets in temperate lakes.  Canadian J. Fisheries Aquatic Science 50: 1728-1737.

__Nürnberg, G.K.__ 1991. Phosphorus from internal sources in the Laurentian Great Lakes, and the concept of threshold external load. J. Great Lakes Research 17: 132-140.

--. 1988. The prediction of phosphorus release rates from total and reductant-soluble phosphorus in anoxic lake sediments. Can. J. Fisheries Aquatic Science 45: 453-462.

--. 1988. A simple model for predicting the date of fall turnover in thermally stratified lakes. Limnology and Oceanography 33: 1190-1195.

--. 1987. A comparison of internal phosphorus loads in lakes with anoxic hypolimnia: laboratory incubations versus hypolimnetic phosphorus accumulation. Limnology and Oceanography 32: 1160-1164.

--. 1987. Hypolimnetic withdrawal as a lake restoration technique. American Society of Civil Engineers, J. Environmental Engineering Division 113: 1006-1017.

__Nürnberg, G.K.__, R. Hartley and E. Davis. 1987. Hypolimnetic withdrawal in two North American lakes with anoxic phosphorus release from the sediment. Water Research 21: 923-928.

__Nürnberg, G.K.__, M. Shaw, P.J. Dillon and D.J. McQueen. 1986. Internal phosphorus load in an oligotrophic Precambrian Shield lake with an anoxic hypolimnion. - Canadian J. Fisheries Aquatic Science 43: 574-580.

__Nürnberg, G.K.__ 1985. Availability of phosphorus upwelling from iron-rich anoxic hypolimnia. Archive Hydrobiologia 104: 459-476.

__Nürnberg, G.K.__ and Peters, R.H. 1984: Biological availability of soluble reactive phosphorus in anoxic and oxic freshwaters.  - Canadian J. Fisheries Aquatic Science 41: 757-765.

--. 1984: The importance of internal phosphorus load to the eutrophication of lakes with anoxic hypolimnia. - Verhandlungen  Internationalen Vereinigung Limnologie 22: 190-194.

__Nürnberg, G.K.__ 1984. The prediction of internal phosphorus load in lakes with anoxic hypolimnia. - Limnology and Oceanography 29: 111-124.

-- 1984. Iron and hydrogen sulfide interference in the analysis of SRP in anoxic waters. - Water Research 20: 369-377.

## Theses

__Nürnberg, G.K.__ 1984. The availability of phosphorus from anoxic hypolimnia to epilimnetic plankton. Ph.D. Thesis, McGill University, Montreal.

__Nürnberg, G.K.__ 1977. Feinstrukturelle Änderungen der Mitochondrien in Gewebekulturzellen unter Anoxie und dem Einfluss von Stoffwechsel-Inhibitoren. (Fine structural changes of mitochondria from tissue culture cells upon anoxia and the influence of metabolic inhibitors.) M.Sc. Thesis, Johann Wolfgang Goethe University, Frankfurt, Germany.

## Presented papers, organized sessions, meetings

__Nürnberg, G.K.__ 2019. Ethical conduct in NALMS' activities. 40 NALMS Symposium, Burlington, Vermont.

__Nürnberg, G.K.__ 2019. Internal Phosphorus Loading Models: A Critical Review. 40 NALMS Symposium, Burlington, Vermont.

__Nürnberg, G.K.__ 2019. Quantification of internal phosphorus loading. Workshop Gew&#228;ssereutrophierung: Strategien zur Restaurierung eutropher Seen. Limno Solutions International at EURAC Research, Bozano, Italy. 

__Nürnberg, G.K.__ 2018. Revisit of the lake restoration technique hypolimnetic withdrawal. 39 NALMS Symposium, Cincinnati, Ohio.

__Nürnberg, G.K.__ 2018. Benefits and optimization of hypolimnetic withdrawal as a lake restoration technique. 61th Great Lakes Conference, Toronto Scarborough, June 18-22, 2018. 

__Nürnberg, G.K.__ 2018. Benefits and optimization of hypolimnetic withdrawal as a lake restoration technique (invited plenary presentation). LAHTI LAKES
2018, Restoration of Eutrophic Lakes: Current Practices and Future Challenges. June 4–6, 2018 Lahti, Finland. 

__Nürnberg, G.K.__ 2018. Investigating the effect of internal phosphorus loading on cyanobacteria: Hypotheses and case studies. 2nd Interdisciplinary Freshwater Harmful Algal Blooms Workshop, April, Toronto, ON.

__Nürnberg, G.K.__, T. Howell and M. Palmer. 2017. 28 Years of impact from central basin hypoxia and internal phosphorus loading on north shore water quality in Lake Erie. 38 NALMS Symposium, Westminster, CO.

__Nürnberg, G.K.__ 2017. Water quality after treatment with lanthanum-modified clay (Phoslock) of urban Henderson Lake, Alberta. 38 NALMS Symposium, Westminster, CO.

__Nürnberg, G.K.__ and R. Fischer. 2017. Internal phosphorus loading and cyanobacteria in Sudbury lakes: a sign of recovery from acid mine history? Society of Canadian Limnologists, Montreal, Jan 2017.

__Nürnberg, G.K.__ 2016. Phoslock - a novel lake treatment in Canada 37nd NALMS Symposium, Banff, AB.

__Nürnberg, G.K.__ 2016. Investigating the effect of internal phosphorus loading on cyanobacteria: Hypotheses & case studies. 33th Congress of the International Association of Limnology, Torino, Italy.

__Nürnberg, G.K.__, T. Howell and M. Palmer. 2016. The potential impact of Central Basin hypoxia and internal loading on north shore water quality in Lake Erie. IAGLR Symposium June  2016, Guelph, Ontario.

__Nürnberg, G.K.__ and B.D. LaZerte. 2016. Water Quality and Capacity for Long Lake, City of Greater Sudbury. Long Lake Stewardship, Sudbury, Ontario. May 29, 2016.

--. 2015. More than 20 years of internal phosphorus load and its effects on polymictic eutrophic Lake Winnipeg, Manitoba. Society of Canadian Limnologists, Ottawa, Jan 2015.

__Nürnberg, G.K.__ and J. Shead. 2014. Internal phosphorus load quantification and effects in Lake Winnipeg, Canada. 35nd NALMS Symposium, Tampa, FL, USA.

--. 2014. Internal phosphorus load assessment in Lake Winnipeg. IAGLR Symposium May 2014, Hamilton, Ontario.

__Nürnberg, G.K.__ 2014. Bright Lake – Pakawagamengan  What’s in its future? Presentation to Bright Lake association, Algoma,.

--. 2013. Cyanobacteria and internal phosporus loading: hypotheses and case studies. 33nd NALMS Symposium, San Diego, CA, USA.

__Nürnberg, G.K.__ and J. Ansker. 2012. Hypolimnetic withdrawal as a possible treatment of internal load in a natural drinking water reservoir in Stockholm, Sweden - an evaluation. 32nd NALMS Symposium, Madison, WI, USA.

__Nürnberg, G.K.__, L.A. Molot and P.S. Loh. 2012. Evidence of internal phosphorus load in Lake Simcoe. IAGLR Symposium May 2012, Cornwall, Ontario.

__Nürnberg, G.K.__ 2011. The quest for adequate phosphorus measurements in lakes. 31st NALMS Symposium, Spokane, WA, USA, Oct 26-28, 2011.

--. Importance of low-level analysis in comparison to sample timing, handling and other methods to obtain representative phosphorus measurements in lake water (invited). National Environmental Monitoring Conference, Bellevue, WA, Aug 15-19, 2011

--. Assessing internal phosphorus load - Approaches & Problems as applied to Lake Winnipeg (invited). Annual science workshop of the Lake Winnipeg Research Council (LWRC), Winnipeg, April 26-27, 2011.

--. Assessing internal phosphorus load -  Approaches & Problems as applied to Lake Winnipeg (Invited). Annual science workshop of the Lake Winnipeg Research Council (LWRC), Winnipeg, April 26th and 27th, 2011.

Verdone, L and __G.K. Nürnberg__. 2011. Determination of the causes of cyanobacteria blooms through water quality monitoring and assessment of phosphorus and nitrogen inputs from the watershed and bottom sediments in Desbarats Lake, Johnston Township. Society of Canadian Limnologists, Toronto, Ontario.

__Nürnberg, G.K.__ 2010. Internal load and sedimentation in phosphorus mass balance models. International Association for Great Lakes, Toronto, Ontario.

__Nürnberg, G.K.__ and J. Milito. 2010. Cyanobacteria blooms in Bright Lake, Ironbridge, ON: How a lake association tries to clean up its lake. Society of Canadian Limnologists, Winnipeg, Manitoba.

__Nürnberg, G.K.__ 2010. Internal phosphorus load and sedimentation in mass balance models. Society of Canadian Limnologists, Winnipeg, Manitoba.

--. Calibrating retention models that predict summer phosphorus concentration in lakes with internal load. 29th NALMS Symposium, Hartford, Connecticut, USA.

--. 2009. The devil is in the sediments: internal phosphorus loading in lakes. (Invited) Annis Water Resources Institute, Grand Valley State University, Muskegon, MI

--. 2009. Restoration options in lakes with internal phosphorus load. (Invited) 36th Aquatic Toxicity Workshop, La Malbaie, Quebec.

--. 2008. Inflow load or concentration: what dictates water quality in a eutrophic shallow urban reservoir? 28th NALMS Symposium, Lake Louise, Alberta.

--. 2008. A Proposed bluegreen algal bloom indicator: Low-Nitrate-Days (LND). 43rd Canadian Association of Water Quality, Burlington, Ontario.

--. 2008. Consulting and science: how to combine the two in Freshwater Research. (Invited) University of Toronto, Scarborough Campus

--. 2007. Difficulties in the determination of internal P load. 27th NALMS Symposium, Orlando, Florida, USA

--. 2007. Assessing internal phosphorus load, problems to be avoided. 30th Congress of the International Association of Limnology, Montreal, Quebec.

--. 2007. Development of the bluegreen algal bloom indicator: Low-Nitrate-Days (LND). 30th Congress of the International Association of Limnology, Montreal, Quebec.

__Nürnberg, G.K.__ & K. Wagner. 2007. Advancements in lake management. Session convener for the 30th Congress of the International Association of Limnology, Montreal, Quebec, Canada

__Nürnberg, G.K.__ 2007. Experience of hypoxia in lakes. Invited participant of the Baltic Sea 2020 Workshop, Björn Carlson Foundation for the Baltic Sea, Lund, Sweden.

--. 2006. Low-Nitrate-Days (LND), a novel indicator of bluegreen algal blooms in lakes. 26th NALMS Symposium, Indianapolis, Indiana, USA

--. 2006. Focus on Fanshawe: A Forum for Local London Environmental Concerns - Fanshawe Lake Water Quality Study (Invited)  The Sierra Club of Canada

--. 2005. How to maximize the benefits of hypolimnetic withdrawal as a lake restoration technique. 25th NALMS Symposium, Madison, Wisconsin, USA (Invited – presentation and chair for special session on Hypolimnetic Withdrawal)

--. 2005. Predicting water quality: how does Lake Simcoe compare to other lakes? (Invited) Lake Simcoe Environmental Management Strategy, ON, Canada

--. 2004. Predicting phosphorus retention in mass balance modeling. (Invited) University of Washington, Seattle, WA USA

--. 2004. Modeling internal phosphorus load and the expected range of summer phosphorus concentration in polymictic lakes. 24th NALMS Symposium, Victoria, BC, Canada

--. 2004. Internal phosphorus loading preventing lake restoration. 29th Congress of the International Association of Limnology, Lahti, Finland (Invited to workshop: Why is it so difficult to restore a lake: unsolved questions in lake restoration)

--. 2004. Quantification of internal phosphorus loading and concentration in shallow lakes. 29th Congress of the International Association of Limnology, Lahti, Finland

--. 2004. Alum the preferred lake restoration method? (Invited) American Fishery Society, Ontario Chapter, Dorset, Ontario

__Nürnberg, G.K.__ and B.D. LaZerte. 2003. A bloom of toxic Planktothrix rubescens in a small urban kettle lake, induced by a lake restoration technique. 23rd NALMS Symposium, Connecticut, USA.

__Nürnberg, G.K.__ and H. Cyr. 2003 Phosphorus (P) exchange between littoral sediments and nearshore water. Fourth International Workshop on Phosphorus in Sediments, Carmona, Spain.

__Nürnberg, G.K.__ and B.D. LaZerte. 2003. A bloom of Planktothrix rubescens in Lake Wilcox, Ontario, probably induced by a lake restoration technique. 22th annual Conference of the Society of Canadian Limnologists, Ottawa.

__Nürnberg, G.K.__ and D. Osgood 2002. In-lake restoration: Alum the preferred method? 22nd NALMS Symposium, Anchorage, Alaska, USA.

Osgood, D. and __G.K. Nürnberg__ 2002. In-lake restoration: Proposed annual alum applications for Lake Mitchell, South Dakota. 22nd NALMS Symposium, Anchorage, Alaska, USA.

__Nürnberg, G.K.__ 2002. Quantification of oxygen depletion in lakes and reservoirs with the hypoxic factor. (Invited) Annual meeting of the American Society of Limnology and Oceanography, Victoria, British Columbia.

--. 2001. Hypolimnetic withdrawal: a technique for long-term water quality improvements in lakes. 21st NALMS Symposium Madison, WI (Invited)

__Nürnberg, G.K.__ and B.D. LaZerte. 2000. Water Quality Modelling. 20th Annual International Symposium of the North American Lake Management Society, Miami, FL (Invited).

--. 2000. Modelling water quality. (Invited) New England Chapter of NALMS, University of Connecticut, Hartford, CN.

--. 2000. Predicting Water Quality. 13th Annual National Conference, Enhancing the States' Lake Management Programs, Chicago, IL (Invited).

__Nürnberg, G.K.__ 2000. Three Presentations in the Expert Forum on Establishing TMDLs: Brownlee Reservoir and the Lower Snake River. Boise, ID (Invited).

--. 1999. Anoxic Factor: ein quantitatives Maß der hypolimnischen Sauerstoffarmut, Theoretical Modeling Conference in Usedom, Germany.

--. 1999. Modelling the effect of development on internal phosphorus loading. ILEC Lake99 Conference, Copenhagen, Denmark.

--. 1998. Modelling the effect of development on annual phosphorus concentrations of lakes including those with anoxic hypolimnia. 18th Annual International Symposium of the North American Lake Management Society, Banff, Alberta. (Chair of sessions: Effects of development on internal phosphorus loading, and Artificial precipitation of phosphorus for lake restoration).

--. 1997. A simple model to calculate the phosphorus and suspended solids removal capacity of stormwater detention ponds. 17th Annual International Symposium of the North American Lake Management Society, Houston, Texas.

--. 1997. Modeling epilimnetic and annual average phosphorus concentration in reservoirs with cold water inputs and hypolimnetic withdrawal. 17th Annual International Symposium of the North American Lake Management Society, Houston, Texas. (Poster).

--. 1997. Removal capacity of phosphorus and suspended solids in stormwater detention ponds, urban lakes and wetlands. 32st Central Canadian Symposium on Water Pollution Research, Burlington, Ontario.

--. 1996. Modeling seasonal phosphorus in lakes with sediment phosphorus release. ASLO'96, Milwaukee, WI. (Session Chair: Sediment derived phosphorus and lake trophy).

--. 1996. Die Wirkung von Sauerstoff, Farbe, Wasserhärte und Eisen auf den Phosphorzyclus in Seen. Umweltforschungszentrum Leipzig-Halle, Sektion Gewässerforschung Magdeburg, Germany (Invited).

--. 1996. Modeling phosphorus in lakes with possible sediment phosphorus release. Near North Environmental Symposium, Northbay, Ontario (Invited).

--. 1996. Coping with water quality problems due to hypolimnetic anoxia in two hardwater lakes and the prevention of these problems in softwater lakes. 31st Central Canadian Symposium on Water Pollution Research, Burlington, Ontario (Invited).

--. 1995. Lake trophy revisited: The importance of morphometry, geochemistry and anoxia. 15th Annual International Symposium of the North American Lake Management Society, Toronto, Ontario. (Session Chair: Lake restoration: When and why?).

--. 1995. Modeling phosphorus in lakes with possible sediment phosphorus release, case studies. 15th Annual International Symposium of the North American Lake Management Society, Toronto, Ontario.

--. 1995. The anoxic factor, a quantitative measure of anoxia and fish species richness. The 14th Annual Meeting of the Society of Canadian Limnologists, Ottawa, Ontario.

--. 1994. The anoxic factor and the number of fish species. 14th Annual International Symposium of the North American Lake Management Society, Orlando, Florida.

--. 1993. Where lake restoration has led to insights in basic limnology: The example of internal phosphorus load. Annual meeting of the American Society of Limnology and Oceanography, Edmonton, Alberta. (Invited)

--. 1993. Phosphorus release from anoxic sediments - what we know and how we can deal with it. 7th Congress of the Spanish Association of Limnologists, Bilbao, Spain, June 1993. (Invited Plenary Speaker)

--. 1993. Characteristics of lakes with internal phosphorus load. 13th Annual International Symposium of the North American Lake Management Society, Seattle, Washington.

--. 1993. The anoxic factor, a quantitative estimate of hypolimnetic anoxia in stratified lakes. 12th annual Conference of the Society of Canadian Limnologists. Trent University, Peterborough, Ontario. (Session Chair: Lake Management)

--. 1992. Application and prediction of the anoxic factor, a quantitative estimate of hypolimnetic anoxia in stratified lakes. 12th Annual International Symposium of the North American Lake Management Society, Cincinnati, Ohio. (Recipient of a foreign speaker travel grant.)

--. 1990. Sediment/Water interactions - Concepts and open questions. 5th International Symposium, The Interactions between Sediments and Water, Uppsala, Sweden.

__Nürnberg, G.K.__ and D. McQueen. 1989. Phosphorus from internal sources in lakes. 32nd Conference on Great Lakes Research, Madison, Wisconsin. (Invited)

__Nürnberg, G.K.__ and P.G. Manning. 1988. The decrease of phosphorus and iron fractions in anoxic sediments and corresponding water gain during anoxic incubation. Second International Workshop on Phosphorus in Sediments, Fiskebackskil, Sweden, Sept. 14-16.

__Nürnberg, G.K.__ 1986. The correlation of anoxic phosphorus release with sediment extractions in several North American lakes. First International Workshop on Phosphorus in Sediments, Vienna, Austria, March 23-26.

__Nürnberg, G.K.__ and M. Shaw. 1985. Phosphorus release from anoxic sediments in a Canadian Shield Lake. 48th annual meeting of the American Society of Limnology and Oceanography, Minneapolis, Minnesota.

__Nürnberg, G.K.__ and R.H. Peters. 1984. Biological availability of soluble reactive phosphorus in freshwaters. Symposium on Phosphorus-Plankton Dynamics in the 27th Conference on Great Lakes Research, St. Catharines, Ontario. (Invited).

--. 1983. The importance of internal phosphorus load to the eutrophication of lakes with anoxic hypolimnia. 22nd Congress of the International Association of Limnology, Lyon, France.

__Nürnberg, G.K.__ and H. L'Heureux. 1982. High hypolimnetic phosphorus concentrations in anoxic Quebec lakes and the availability to epilimnetic plankton. First annual meeting of the Society of Canadian Limnologists, Ottawa.

__Nürnberg, G.K.__ 1982. Falsification of current phosphorus budget models for lakes with anoxic hypolimnia and a proposed computation of internal phosphorus loading. 45th annual meeting of the American Society of Limnology and Oceanography, Raleigh, North Carolina.

