---
title: "Past Projects"
toc: true
---

### 2020- {#y2020}

#### Management options for Moncton’s drinking water reservoirs. (2021-2022)
__Client:__ City of Moncton, New Brunswick  
__Scope:__ Two of the drinking water reservoirs of the City of Moncton experienced a cyanobacteria bloom in the fall of 2017. Freshwater Research investigated possible remediation options and critically evaluated abatement options to diminish the danger of such blooms. Several years of limnological monitoring data are combined with climate records to determine the future risk of cyanobacteria blooms in the context of climate variability and change.

#### Swan Lake water quality management (2021-2022)
__Client:__ Town of Markham, Ontario  
__Scope:__  Review and update of a management plan for Swan Lake, based on 1993-2021 data on water quality, water fowl, previous lake interventions, and phosphorus mass balance modelling.

#### Management options for Moncton’s drinking water reservoirs. (2020-2021)
__Client:__ City of Moncton, New Brunswick  
__Scope:__ Two of the drinking water reservoirs of the City of Moncton experienced a cyanobacteria bloom in the fall of 2017. Freshwater Research investigated possible remediation options and critically evaluated abatement options to diminish the danger of such blooms. Several years of limnological monitoring data are combined with climate records to determine the future risk of cyanobacteria blooms in the context of climate variability and change.

#### Bilan de phosphore et plan d'action du Lac Echo, Saint-Hippolyte (Phosphor mass balance and action plan for Echo Lake, Saint-Hippolyte, Quebec) (2020-2021) 
__Client:__ Groupe Hémisphères, Quebec   
__Scope:__  A management and restoration plan for mesotrophic Lac Echo is updated, based on previous and recent monitoring and phosphorus mass balance calculations.

### 2010-2019 {#y2010}

#### Swan Lake water quality management (2019-2020)
__Client:__ Town of Markham, Ontario  
__Scope:__  A comprehensive management plan is assembled for Swan Lake, based on 1993-2018 data on water quality, water fowl, previous lake interventions, and phosphorus mass balance modelling.

#### Lac Maskinongé – Mont-Tremblant, Quebec, support of a restoration feasablity study including P mass balances, continued. Joint task with Groupe Hémisphères (2019-2020) 
__Client:__ Service de l’environnement et du développement durable, Mont-Tremblant, Quebec   
__Scope:__  A previously assembled management and restoration plan for eutrophic Lac Maskinongé is updated, based on monitoring in 2019, renewd phosphorus mass balance calculations, and feasibility analysis.

#### Support for monitoring with subsequent reporting on the water quality of Moncton’s drinking water reservoirs in 2019. (2019-2020)
__Client:__ City of Moncton, New Brunswick  
__Scope:__ Two of the drinking water reservoirs of the City of Moncton experienced a cyanobacteria bloom in the fall of 2017. Continued monitoring establishes water quality conditions to pro-actively address any potential cyanotoxin-related issues. 

#### Support for monitoring and study on the possible effects of internal and external phosphorus loading on the water quality of a mining pond. Joint task with AlbaCon Environmental (2019-2020)
__Client:__ An undisclosed mine,  
__Scope:__ A pro-active study to help develop a greater understanding of the phosphorus loading (internal and external) and cycling in the treatment ponds of a mine in order to develop a management plan should additional mitigation activities be required in the future.

#### Determination of the water quality and phosphorus content after a Phoslock treatment in Serpentine Lake, London, using a phosphorus mass balance analysis (2018-2019)
__Client:__ Royal Parks, London, UK.    
__Scope:__ A phosphorus mass balance analysis is to determine the success of a Phoslock treatment after one year of post-treatment monitoring.

#### Phytoplankton in Swan Lake in the 5th year after a Phoslock treatment (2018)
__Client:__ Town of Markham, Ontario  
__Scope:__  Data from an extensive phytoplankton monitoring program in Swan Lake were interpreted with respect to water quality development 5 years after a Phoslock treatment.

#### Restoration options for Moncton’s drinking water reservoirs. (2018-2019)
__Client:__ City of Moncton, New Brunswick  
__Scope:__ Two of the drinking water reservoirs of the City of Moncton experienced a cyanobacteria bloom in the fall of 2017. Freshwater Research investigated possible remediation options to diminish the danger of such blooms in the near future.

#### Lac Maskinongé – Mont-Tremblant, Quebec, support of a restoration feasablity study including P mass balances. Joint task with Groupe Hémisphères (2018-2019) 
__Client:__ Service de l’environnement et du développement durable, Mont-Tremblant, Quebec   
__Scope:__  A management and restoration plan for eutrophic Lac Maskinongé is assembled, based on monitoring, phosphorus mass balance calculations and feasibility analysis.

#### Leonard Lake, Township of Muskoka Lakes, water quality in 2017 and 2018 and potential effecs of further development plans (2018) 
__Client:__ Leonard Lake Stakeholders Association  
__Scope:__ Limnological (lake-related) information including monitoring data of 2017 and observations in 2018 in addition to professional knowledge were used to determine potential effects of future development on steep, slopes with low soil cover on Leonard Lake water quality. 

#### Determination of the feasablity of a Phoslock treatment in the Pebley and Harthill reservoirs by a phosphorus mass balance analysis (2017-2019)
__Client:__ Canal and River Trust, UK.    
__Scope:__ Recommendations pertaining the sediment treatment of two reservoirs along the Chesterfield Canal, Derbyshire, England.

#### Critical review of the District of Muskoka Draft Official Plan - "Water Quality" Provisions, Official Plan Amendment 45 and recommendations (2017-2018)
__Client:__ Friends of Muskoka, Ontario    
__Scope:__ Recommendations pertaining to lake monitoring by the District Municipality of Muskoka and other suggested changes in the OPA 45 text for the enhancement of lake protection.

#### Support for the Lake Wilcox Management Plan Update (2017-2018)
__Client:__ Town of Richmond Hill, Ontario    
__Scope:__ Help update the Lake Wilcox Management Plan in the role of peer reviewer and adviser to the lead consultant, AECOM.

#### Management of the cyanobacteria bloom in Moncton’s drinking water reservoirs. (2017-2018)
__Client:__ City of Moncton, New Brunswick  
__Scope:__ Two of the drinking water reservoirs of the City of Moncton experienced a cyanobacteria bloom in the fall of 2017. Freshwater Research investigated potential causes with the goal of future prevention and remediation.

#### Limnological assessment of Swan Lake in the 5th year after a Phoslock treatment, including lake level fluctuations (2017-2018)
__Client:__ Town of Markham, Ontario  
__Scope:__ Swan Lake is a highly eutrophic urban lake with a long history of cyanobacterial blooms (“bluegreen blooms”). A monitoring plan was assembled and supervised that included water fowl population assessment and weather related information. Based on collected water quality information recommendations for Swan Lake's further remediation and treatment are to be proposed.  

#### Roxton Pond (Lac Roxton), Quebec, support of a restoration feasablity study including P mass balances. Joint task with T2 Environnement and Daniel Néron (2017-2018) 
__Client:__ Comité d’environnement du Lac Roxton (CELR)  
__Scope:__  A management and restoration plan for eutrophic Roxton Pond is assembled, based on monitoring, phosphorus mass balance calculations and feasibility analysis.

#### Assessment of the Coeur d’Alene, ID, Indian Reservation water quality management plan (2017) 
__Client:__ Coeur d’Alene Tribe and Avista Corporation  
__Scope:__  Provided water quality variables were reviewed and evaluated, the usefulness of the current monitoring plan investigated and recommendations for future monitoring offered.

#### The carrying capacity of Leonard Lake, Muskoka, considering potential internal phosphorus load (2017) 
__Client:__ Leonard Lake Stakeholders Association  
__Scope:__  The carrying capacity of Leonard Lake, Township of Muskoka Lakes, was investigated from previous modeling studies, lake characteristics, limnological (lake-related) information including monitoring data, and general professional knowledge. 

#### Internal phosphorus (P) load assessment in Georgian Bay embayments to improve understanding about P sources and onshore-offshore productivity gradients (2016-2017) 
__Client:__ Freshwater Program of (ECCC) - Lake Simcoe, Eastern Georgian Bay, Ontario  
__Scope:__ Phytoplankton communities in embayments along the coast of Eastern Georgian Bay, EGB, include variable amounts of cyanobacteria that can form large blooms in productive embayments such as Sturgeon Bay. This project seeks to explore possible sensitivity to internal loading over a range of EGB locations, based on basin characteristics and past and ongoing water quality monitoring. In addition to the collection of factors that indicate the possibility of the occurrence of sediment P release, quantitative approaches are to be applied to determine how much this process can affect EGB water quality along a gradient of development by estimating internal load in several embayments.  

#### Limnological assessment of Swan Lake in the 4th year after a Phoslock treatment, including water fowl abundance (2016-2017)
__Client:__ Town of Markham, Ontario  
__Scope:__ Swan Lake is a highly eutrophic urban lake with a long history of cyanobacterial blooms (“bluegreen blooms”). A monitoring plan was assembled and supervised that included water fowl population assessment. Based on collected water quality information recommendations for Swan Lake's further remediation and treatment are to be proposed.  

#### Determination of phosphorus budgets in Henderson Lake, Alberta, before and after a Phoslock (lanthanum modified clay) treatment (2016-2017)  
__Client:__ Phoslock Water Solutions Ltd, Sydney, NSW 2000, Australia.  
__Scope:__ Henderson Lake, Alberta is to be treated with Phoslock (lanthanum modified clay) to abate its internal phosphorus loading. A pre- and post- application study is to confirm treatment effectiveness. In particular, a phosphorus budget prior and after the Phoslock treatment are to be established to determine the effectiveness of Phoslock in reducing internal P load.

#### Support for an update of Lake Wilcox Interim Report Card for 2011-2015 (2016)
__Client:__ Town of Richmond Hill, Ontario    
__Scope:__ Provision of models and spreadsheet formulas to determine annual changes in hypolimnetic anoxia. Investigation of hydrological variability and annual external phosphorus inputs from specific inflows. Explanation and interpretation of phytoplankton data.

#### Phoslock (lanthanum modified clay) internal phosphorus loading treatment in Canada: regulations, experience, and effects (2016)
__Client:__ British Columbia Ministry of Environment, Nanaimo, BC and Elk Lake restoration steering committee.    
__Scope:__ Assembling of a presentation file on Phoslock treatment. It includes experiences in Canadian provinces, case studies, specifics (use in drinking water lakes), how its application is regulated, and a review of any negative impacts to ecosystem functions (i.e., habitat, food chain etc.). It explores the characteristics of Elk Lake that make this technique applicable and preferred.        

#### Evaluation of remediation options for Elk/Beaver Lake, Victoria BC (2015-2016)
__Client:__ British Columbia Ministry of Environment, Nanaimo, BC    
__Scope:__ Review and update of the relative importance of external versus internal phosphorus load concerning cyanobacterial blooms. Description of several potential lake remediation techniques and provision of details and justification for the choice of the preferred option.

#### Monitoring support, limnological and capacity assessment for Long Lake, Greater Sudbury Area, Ontario (2014-2015)
__Client:__ Long Lake Association, Ontario    
__Scope:__ Long Lake has experienced some late summer and fall phytoplankton blooms in the past, and the Long Lake Association is concerned about the future water quality of Long Lake. Freshwater Research was asked to initiate a lake assessment study with the goal of determining Long Lake’s capacity for development.

#### Review of monitoring data for 2013 and 2014, and recommendations for future monitoring in Lac des Écorces, Quebec (2015)
__Client:__ Township of Barkmere, Laurentian, Quebec    
__Scope:__ Lac des Écorces (Bark Lake) limnological assessment, including comparisons between years and possible trend analysis to inform future monitoring needs.

#### Water quality in four Algoma watersheds based on monitoring in 2013-2015 (2015)
__Client:__ Central Algoma Freshwater Coalition, Bruce Mines, Ontario    
__Scope:__ Water quality was assessed of four monitored watersheds including the Desbarats Lake Watershed (includes Reserve Lake and McCluskie Lakes), the Stobie Creek Watershed (includes Caribou Lake), Bright Lake Watershed (includes Big Basswood Lake, and the Day Lakes) and the Little Thessalon River Watershed. Almost all lakes in this watershed had experienced cyanobacteria blooms. Future monitoring and management actions were suggested.

#### Influence of upwelling and onshore circulation of low oxygen water on the coastal water quality of the north shore of Lake Erie's Central Basin (2015)
__Client:__ Ontario Ministry of Environment and Climate Change  
__Scope:__ In an attempt to improve understanding of the influence of Lake Erie Central Basin open water on north shore water quality, the report presents a review of the technical limnological literature followed by an analysis of publicly available Lake Erie data.

#### Gap analysis for nutrients in the area of the Lower Thames Valley Conservation Authority, Ontario (2015)
__Client:__ Lower Thames Valley Conservation Authority, Chatham, Ontario,  
__Scope:__ An analysis of knowledge and data gaps in the current water quality and flow monitoring program was conducted to provide informed recommendations for future monitoring of the Lower Thames River and other creeks and rivers in the jurisdiction of the LTVCA flowing into Lake Erie and Lake St. Clair.

#### Evaluation of the Swan Lake PhoslockTM treatment in the 2nd year (2014-2015)
__Client:__ Town of Markham, Ontario  
__Scope:__ Swan Lake is a highly eutrophic urban lake with a long history of cyanobacterial blooms (“bluegreen blooms”). Based on collected water quality information a PhoslockTM  treatment was proposed.  A total of 25.2 tonnes of PhoslockTM at a rate of 4.6 metric tonnes/ha was applied from 29 April – 1 May 2013. A detailed post-treatment monitoring plan was put together and the effects and efficiency of the treatment in two post-treatment years was evaluated.

#### Water Quality 2014 evaluation in Bright Lake (Pakawagamengan): Potential causes of cyanobacteria blooms (2014)
__Client:__ Bright Lake Association Inc., Ironbridge, ON  
__Scope:__ Cyanobacteria blooms in late summer and fall were irregular in years of 2008-2014. Possible causes that support blooms in specific years were investigated.

#### Assessment of potential changes due to mining and other anthropogenic activities in several lakes, BC (2014)
__Client:__ British Columbia Ministry of Environment, Williams Lake, British Columbia  
__Scope:__ Determining the water quality and potential trophic state changes in several lakes in response to various manipulations, including activities related to mining.

#### Water Quality Assessment in the Thames River Watershed (2013-2014)
__Client:__ Upper Thames River Conservation Authority, London, Ontario  
__Scope:__ Based on long-term water quality and hydrological data of the Thames River and its tributaries, a better understanding of nutrient sources, fate, and delivery throughout the Thames River system is acquired. Results are to aid remediation programs in the watershed.

#### Quantification of the internal phosphorus load in Lake Winnipeg (2013-2014)
__Client:__ Lake Winnipeg Basin Stewardship Fund, Environment Canada and The Lake Winnipeg Foundation  
__Scope:__ Internal phosphorus inputs were quantified using long-term P monitoring data and results of past studies. Several approaches were used including water column increases of P concentration throughout the summer, mass balance calculations, and sediment P content and P release rates.

#### Evaluation of the Swan Lake PhoslockTM treatment (2013-2014)
__Client:__ Town of Markham, Ontario  
__Scope:__ Swan Lake is a highly eutrophic urban lake with a long history of cyanobacterial blooms (“bluegreen blooms”). Based on collected water quality information a PhoslockTM  treatment was proposed.  A total of 25.2 tonnes of PhoslockTM at a rate of 4.6 metric tonnes/ha was applied from 29 April – 1 May 2013. A detailed post-treatment monitoring plan was put together and the effects and efficiency of the treatment evaluated.

#### Evaluation of the Fish Lake Mitigation Proposal by the Taseko Prosperity Gold-Copper Project (2013)
__Client:__ British Columbia Ministry of Environment, Impact Assessment, Williams Lake, BC  
__Scope:__ A mine is to be built around, rather than through, Fish Lake to prevent the loss of the lake and its heritage to First Nations. As the mine intends to stop inflow and outflow to the lake a number of management strategies were proposed, including the recycling of its water. The impact of these proposed mitigation strategies on the current water quality of Fish Lake were evaluated.

#### Water quality in Bright Lake, ON (2013)
__Client:__ Bright Lake Association Inc., Ironbridge, ON  
__Scope:__ Problems: Cyanobacteria blooms in late summer and fall. A previously introduced monitoring plan served for a basic limnological assessment, including water and sediment phosphorus sampling for internal load analysis. Quantification of anoxia, external and internal load for 2011-2013.

#### Monitoring support, limnological and capacity assessment for Lac des Écorces, Quebec (2010-2013)
__Client:__ Township of Barkmere, Laurentian, Quebec  
__Scope:__ Lac des Écorces (Bark Lake) monitoring support, limnological assessment and phosphorus budget modeling was provided with the goal of determining lake capacity for shoreline and road development. Available and new data from Bark Lake and its many upstream lakes were collected from municipalities, lake associations and the ministries, including water quality data sets, flow rates, number of septic systems, and other development as input to the model and potential validation of monitored data of the major inflows. In this way, a capacity study of the larger watershed including Bark Lake and the upstream watercourses was attempted. Several approaches used in Quebec and Ontario watersheds were investigated and applied.

#### Monitoring support and limnological assessment for Desbarats Lake, ON (2010-2013)
__Client:__ Township of Johnson, Desbarats, ON  
__Scope:__ A history of summer and fall algal blooms and turbid water, mostly from Cyanobacteria blooms exists. The causes of the low water quality are to be determined in this oligomictic, meso- to eutrophic lake.

#### The evaluation of hypolimnetic withdrawal as a probable treatment for the Bornsjön Reservoir internal phosphorus load (2011-2012)
__Client:__ Stockholm Vatten (Water) Co, Water production, Waterworks Process Development  
__Scope:__ Vatten is a municipal company that produces and distributes drinking water to the city of Stockholm, Sweden. Lake Bornsjön is a water reserve that suffers from internal load. Although external P load and their sources were mitigated since the mid 80’s the lake still shows symptoms of eutrophication. Of all restoration techniques that combat internal load, the restoration technique of hypolimnetic withdrawal was singled out as potentially applicable. Feasibility was to be determined from previously accumulated monitoring data and limnological characteristics of Bornsjön Reservoir.

#### Swan Lake limnological assessment and recommendations for treatment (2011-2012)
__Client:__ Town of Markham, Ontario  
__Scope:__ Swan Lake is a highly eutrophic urban lake with a long history of cyanobacterial blooms (“bluegreen blooms”). To assess the potential threat of toxic blooms to lake users, a monitoring plan was assembled and supervised. Based on collected water quality information recommendations for Swan Lake's remediation and treatment were proposed.

#### Quantification of the internal phosphorus load in Lake Simcoe to improve phosphorus budgets (2010-2012)
__Client:__ Lake Simcoe Clean-Up Fund, Joint project with project manager Lewis Molot, York University, Ontario  
__Scope:__ Internal phosphorus inputs were quantified by two different approaches. The first approach used P monitoring data collected for Lake Simcoe since the early 1980s to determine past internal inputs. The second approach relied on measuring P release from lake sediments during laboratory incubations and then extrapolating the release rates to the lake taking into account changes in temperature and anoxia. <http://www.iaglr.org/jglr/release/39/2013.03.016_nurnberg.php>

#### A Study to review and update the current “Lake Wilcox Remediation Strategy” which includes recommendations for future management and monitoring for the protection and enhancement of Lake Wilcox (2011)
__Client:__ Town of Richmond Hill, Ontario  
__Scope:__ The update is to include recommendations for future management actions and monitoring practices for the protection and enhancement of Lake Wilcox through an analysis of existing monitoring data, a review of current limnological literature with respect to lake and phosphorus management and recommendations for application of available technologies in particular phosphorus remediation technologies for possible implementation within the watershed. The study is to analyze and report on the existing conditions, as a result of the implementation of the original strategy recommendations, and to identify and recommend future management practices and potential phosphorus technologies that the Town may reasonably implement to reduce external and internal loading of phosphorus to Lake Wilcox.

#### Lakeshore capacity study for Bright and Basswood Lake, ON (2010-2011)
__Client:__ Town of Huron Shores, Ironbridge, ON  
__Scope:__ A lake shore capacity model such as that developed by the Ontario Ministry of the Environment (MOE) or the District of Muskoka will be employed to determine the sources of phosphorus entering the lakes (external phosphorus load). Such a model can also estimate pre-development water quality and determine, whether any further development around the lake would noticeably reduce its present water quality. Internal phosphorus load will be incorporated in shallow mesotrophic Bright Lake as described in Nürnberg & LaZerte 2004 and results of such a model will be compared to those of a more simply estimated internal load by the typical MOE capacity model equations. In addition to the phosphorus mass balance, late-summer volumetric dissolved oxygen concentration will be assessed in deep oligotrophic Basswood Lake to determine its manageability for Lake Trout, according to the Ontario Ministry of Natural Resources guidelines.

#### Limnological assessment and potential remediation options for Bright Lake, ON (2009-2011)
__Client:__ Bright Lake Association Inc., Ironbridge, ON  
__Scope:__ Problems: Cyanobacteria blooms in late summer and fall. Setting up a monitoring plan to serve for a basic limnological assessment, including water and sediment phosphorus sampling for internal load analysis. Quantification of anoxia, external and internal load. Support in securing grants from governmental agencies.

#### Water quality assessment and potential remediation options for Four Wells Lake, ON (2009-2011)
__Client:__ The Club Willowells, Waterloo, ON  
__Scope:__ Cyanobacterial blooms in some summers. Setting up a monitoring plan to serve for a basic limnological assessment, including water and sediment phosphorus sampling for internal load analysis. Quantification of external and internal load. Four Wells includes a series of small ponds in a park-like setting connected to tributaries of the Grand River in southern Ontario.

#### Monitoring support for internal phosphorus load estimation in Lac Nairne, Quebec (2009-2010)
__Client:__ Municipalité de St-Aimé-des-Lacs, Quebec  
__Scope:__ Supervision of various monitoring approaches that are to be used to determine sediment released phosphorus which contributes to cyanobacterial blooms in this otherwise oligotrophic lake.

#### Assessment of potential remediation options to diminish internal phosphorus load in Bouchie Lake, BC (2009-2010)
__Client:__ British Columbia Ministry of Environment, Williams Lake, BC  
__Scope:__ Problems: Summer and winter fishkills and cyanobacteria blooms. Based on previously collected water quality data, studies, and reports a limnological assessment was conducted for the shallow but often hypoxic Bouchie Lake and possible remediation options were presented. In a further study, internal phosphorus load was estimated from sediment fractions and in situ phosphorus increases and its effect on Bouchie Lake water quality evaluated.

### 2000-2009 {#y2000}

#### Review and revision of the report: “Water quality in the Grand River Watershed: Current condition and trends (2003 – 2008)” (2009)
__Client:__ The Grand River Conservation Authority, ON  
__Scope:__ Technical review, increase of readability, and recommendations for further investigations including nutrient loading analysis, evaluation of the effect of the reservoirs on stream water quality, and the evaluation of seasonality.

#### Modeling future scenarios based on 15 years of water quality to determine the TMDL in Cherry Creek Reservoir, CO (2006-2009)
__Client:__ Cherry Creek Basin Water Quality Authority, Greenwood Village, Denver, Colorado.  
__Scope:__ Development and validation of a steady state annual mass-balance model to determine permissible phosphorus loadings to the Cherry Creek Reservoir. Components involving internal fluxes (sedimentation and internal load) were used to predict July-September total phosphorus (TP) and chlorophyll averages. Based on the analysis of 15 years of data including phosphorus, chlorophyll and hydrology a methodology that considers average inflow TP concentration (instead of a load) as control variable was proposed. Further, a significant regression of seasonal average chlorophyll on average inflow TP concentration was determined and proposed to be used for the establishment of a chlorophyll standard.

#### Internal load estimates for the Rice Creek Watershed District SW Urban Lakes Study, MN (2007-2008)
__Client:__ Emmons & Olivier Resources, Inc.  
__Scope:__ For 12 lakes in the Minneapolis, St. Paul Area, MN, sediment fractionation provided information for the determination of internal load and its contribution to the total phosphorus concentration of these lakes.

#### Surface Water Treatment Plan for the Coves in London, ON (2006-2008)
__Client:__ The Friends of the Coves Subwatershed, Inc., London Ontario, Canada  
__Scope:__ Determination of limnological characteristics of the Cove ponds and development of a technical implementation plan for surface water treatment.

#### Evaluation of the impact of future increased sulfur from old mining diversions to Trout Lake, MI (2006-2007)
__Client:__ State of Minnesota, Department of Natural Resources and Minnesota Pollution Control Agency  
__Scope:__ Sediment phosphorus release rates are expected to increase with sulfur additions. Simple mass balance modeling of internal P load resulting from increased sulfur is used to quantify likely impacts on the water quality of Trout Lake, MN.

#### Heney Lake, Quebec, Restoration Recommendations, Review (2006-2007)
__Client:__ Le Comité Paritaire du Lac Heney  
__Scope:__ Review of the recommendations for a proposed iron chloride treatment of the lake by estimating the potential for internal P load and hypoxia.

#### Comprehensive analysis of recovery of eutrophied lakes, Finland (CARE) (2004-2007)
__Client:__ Pyhäjärvi Institute, University of Turku, Geological Survey of Finland.  
__Scope:__ An international multidisciplinary team uses Lake Pyhäjärvi in southwest Finland as a case study to evaluate the recovery from eutrophication. Freshwater Research will support following activities: 1. Determination of the importance of internal phosphorus loading in the eutrophication of Lake Pyhäjärvi, 2. Long-term analysis of lake water quality with respect to hydrological and climatic conditions, and 3. Evaluation of present restoration attempts and proposal of future options.

#### Application of the German nutrient model MONERIS to Canadian watersheds (2002-2007)
__Client:__ Dr. Patricia Chambers, National Water Research Institute, Burlington, ON, Canada.  
__Scope:__ Joint collaboration with Dr. Horst Behrend, the Institute for Freshwater Ecology and Inland Fisheries in Berlin, Germany. The watershed model MONERIS has been developed for the predictions of phosphorus and nitrogen in large European watersheds. Its application to more pristine Canadian watersheds is being tested.

#### Reservoir water quality treatment study II, Upper Thames River, ON (2005-2006)
__Client:__ Upper Thames River Conservation Authority, London Ontario, Canada and the Sierra Club, Canada.  
__Scope:__ Examine existing information on upstream (of Fanshawe Reservoir) river sections of the Upper Thames River, its tributaries and reservoirs, including those at St. Mary's, Mitchell and Stratford, propose and supervise supplemental sampling and provide recommendations as to the most effective water quality treatment options for these sections, using a watershed modeling approach.

#### Water quality trends of Lake Wilcox, ON (2005)
__Client:__ Michalski Nielsen Associates, Bracebridge, Ontario.  
__Scope:__ Provide a long-term statistical analysis of water quality trends in Lake Wilcox Ontario using 14 years of available data, including a comparison of pre- to post-treatment water quality with respect to a destratification treatment.

#### Reservoir water quality treatment study I, Upper Thames River, ON (2004-2005)
__Client:__ Upper Thames River Conservation Authority, London Ontario, Canada and the Sierra Club, Canada.  
__Scope:__ Examine existing information on Fanshawe, Wildwood and Pittock Reservoirs on the Upper Thames River, propose and supervise supplemental sampling and provide recommendations as to the most appropriate water quality treatment options for each of the three lakes, using a phosphorus budget approach.

#### Water quality trends of Lake Wilcox, ON, in dependence of climatic conditions (2003)
__Client:__ Michalski Nielsen Associates, Bracebridge, Ontario.  
__Scope:__ Provide a long-term statistical analysis of water quality trends in relation to flow rates and other hydrological conditions in Lake Wilcox, Ontario.

#### Restoration Options for the former sewage lagoon, Morgan Pond, Muskoka (2002-2003)
__Client:__ Pam Carnochon,The Morgan House, Huntsville, Ontario.  
__Scope:__ Morgan Pond is a former sewage lagoon that is to be rehabilitated for contact recreation. Based on the evaluation of water and sediment quality an alum treatment is proposed.

#### Park Lake, the creation of an urban lake in Markham, ON (2000-2003)
__Client:__ Michalski Nielsen Associates, Bracebridge, Ontario for Neamsby Investments Inc.  
__Scope:__ Limnological understanding and modeling is used to guide the design and maintenance of an urban lake to be created in the Rouge River watershed, City of Markham, Ontario. Water quality is predicted from current quality and flow data of the upstream waters and future changes due to development.

#### Limnological and Management Assessment of Lake Lynn Louise, WI (2002)
__Client:__ Dr. James Michaels, Oconomowoc, Wisconsin.  
__Scope:__ Determine the best method for the remediation of Lake Lynn Louise with a detailed evaluation of Sulfur Dioxide (SO2) addition.

#### Lake Mitchell, SD, Water Quality Improvement Program (2001-2002)
__Client:__ With Ecosystem Strategies for the Town of Mitchell, South Dakota.  
__Scope:__ Evaluation and modeling of existing lake/watershed system to be used to recommend a remedial treatment system, under special consideration of alum addition.

#### Water quality trends of Lake Wilcox, ON (2001)
__Client:__ Michalski Nielsen Associates, Bracebridge, Ontario.  
__Scope:__ Provide a long-term statistical analysis of water quality trends in Lake Wilcox Ontario using ten years of available data.

#### Lower Boise River and Brownlee Reservoir, ID, TMDL, total maximum daily loads (1998-2001)
__Client:__ The City of Boise, Idaho.  
__Scope:__ Facilitating the development of total phosphorus standards for the Brownlee Reservoir on the Snake River above the Hells Canyon Complex via field studies, long-term data evaluation, and modeling. Limnological assessment of Brownlee Reservoir with special emphasis on hypoxia, anoxia, and vertical fluxes of phosphorus (sedimentation and internal phosphorus loading). Mass balance and empirical modeling of phosphorus average concentrations, algal biomass, turbidity, hypoxia and anoxia.

#### Predicting Water Quality, Chapter 5 in Managing Lakes and Reservoirs (1998-2001)
__Client:__ Joint project of the North American Lake Management Society, US-EPA and Terrene Institute.  
__Scope:__ Possible ways of modeling water quality in lakes and reservoirs with special emphasis on nutrients and algae biomass (incl. TMDL's) are discussed for the interested layman and professional.

#### Suburban Development: Review of pollutants in surface runoff and their remediation (2000)
__Client:__ Michalski Nielson Associates, Ontario.  
__Scope:__ Literature review of the major pollutant concentrations in urban, suburban and commercial stormwater runoff. The effectiveness of common and recently developed engineering BMPs (Best Management Practices) on the reduction of these pollutants is also examined.

#### Cherry Creek Reservoir, CO, TMDL, total maximum daily loads (2000)
__Client:__ Cherry Creek Basin Water Quality Authority, Greenwood Village, Denver, Colorado.  
__Scope:__ Expert advice at the hearing on the setting of phosphorus and chlorophyll standards and phosphorus TMDLs.

#### Modeling future scenarios for implementation of TMDLs in Cherry Creek Reservoir (2000)
__Client:__ Cherry Creek Basin Water Quality Authority, Greenwood Village, Colorado.  
__Scope:__ Development of a steady state annual mass-balance model to determine permissible phosphorus loadings to the Cherry Creek Reservoir. Components involving internal fluxes (sedimentation and internal load) as determined by the Time Dynamic Model (previous project) were used to predict July-September TP averages. Scenarios, modeled according to past 40 year hydrology and future projections of development, predicted lowest July-September TP averages when both, external and internal phosphorus sources were decreased.

#### Investigation of causes for the bloom of Planktotrix rubescens in Lake Wilcox (2000)
__Client:__ Town of Richmond Hill, Ontario.  
__Scope:__ Description of the development of a Planktothrix (Oscillatoria) rubescens bloom in winter and spring 1998-99. Evaluation of the possible causes, in particular the two in-lake restoration techniques, hypolimnetic aeration and whole water-column destratification or mixing.

#### Development of a time dynamic model for Cherry Creek Reservoir, CO (1999-2000)
__Client:__ Cherry Creek Basin Water Quality Authority, Greenwood Village, Colorado.  
__Scope:__ Development of a time-dynamic (weekly) model for Cherry Creek Reservoir (CCR) that quantifies (1) how in-lake total phosphorus concentration (TP) in polymictic CCR is influenced by external phosphorus inputs and internal processes; and (2) how in-lake nutrient concentrations influence algal biomass. Quantification of factors regulating in-lake TP and chlorophyll a (Chl) during July to September are emphasized to facilitate the establishment of Chl and TP targets.

#### Suitability of empirical models in the predictability of in-lake restoration techniques (1999-2000)
__Client:__ Institute of Freshwater and Fish Ecology, Berlin, Germany.  
__Scope:__ External adviser for graduate studies concerning modelling and fieldwork assessing the predictability of in-lake restoration techniques. Evaluation of Hypolimnetic Withdrawal, as a restoration technique in stratified reservoirs and lakes in Europe and North America.

#### Lake Wilcox longterm limnological assessment and evaluation of in-lake management (1999-2000)
__Client:__ Town of Richmond Hill, Ontario.  
__Scope:__ Assessment of the water quality (1986-1999) of Lake Wilcox, a small urban lake in the vicinity of the metropolitan Toronto. Determination of the effect of two in-lake restoration techniques, hypolimnetic aeration and complete destratification on water quality in general and internal load reduction in particular.

### 1990-1999 {#y1990}

#### Review of water quality standards and phosphorus loads in Cherry Creek Reservoir, CO (1998-1999)
__Client:__ Cherry Creek Basin Water Quality Authority, Greenwood Village, Colorado.  
__Scope:__ Review of phosphorus and chlorophyll standards for future management of the polymictic flood control reservoir. Review and modeling of the phosphorus loads entering Cherry Creek from the watershed (external load) and the reservoir bottom (internal load).

#### Impact of a proposed nursery on South Lake, ON (1998)
__Client:__ South Lake Association, Haliburton, Ontario.  
__Scope:__ Evaluation of the impact of a proposed greenhouse nursery on South Lake water quality, using phosphorus modeling.

#### Restoration options for Brome Lake, Quebec (1997-1998)
__Client:__ Town of Brome Lake, Quebec.  
__Scope:__ Assessment of phosphorus cycle, especially sediment released phosphorus, based on previously collected data. Computation and comparison of phosphorus loads (internal versus external) and determination of their impact on P concentrations and algae blooms. Evaluation of restoration options pertaining to the watershed and the lake itself (in-lake restoration).

#### Lake quality assessment of South Lake in Haliburton, ON (1996-1998)
__Client:__ South Lake Association, Haliburton, Ontario.  
__Scope:__ Limnological assessment with available and newly collected data; application of a phosphorus budget model to evaluate the importance of external (development) and internal (from anoxic sediments) phosphorus sources.

#### Complete revision of the Water Quality Computer Model of the District of Muskoka, ON (1996-1998)
__Client:__ District Municipality of Muskoka, Ontario.  
__Scope:__ Revision of a P mass balance model to predict predevelopment, present and future planning scenarios with consideration of internal P sources in Muskoka lakes, to help establishing development capacities on lakes and predict the impact on recreational water quality.

#### Productivity in brownwater lakes (1996)
__Client:__ Department of Fisheries and Oceans, Sault St. Marie, Ontario.  
__Scope:__ Study of the relationships between long-term average concentrations of humic acids, measured as water colour, dissolved organic carbon (DOC) or Secchi disk transparency and trophic state variables with data from more than 600 clear and coloured freshwater lakes collected from the literature.

#### Evaluation of the water quality of Standley Lake, CO, a high-elevation drinking-water reservoir, with special emphasis on oxygen depletion (1996)
__Client:__ City of Arvada, Colorado.  
__Scope:__ Evaluation of water quality from nutrient and algal biomass concentration of the surface water and from oxygen depletion of the bottom water. Determination of the longterm phosphorus budget of the reservoir, complicated by cold inflow from several canals draining a large watershed, hypolimnetic withdrawal and anoxic P release from the sediments. Prediction of summer epilimnetic and annual average P.

#### Trophic state evaluation of Lake Wilcox (1995-1996)
__Client:__ Town of Richmond Hill, Ontario, in cooperation with Michael Michalski Associates  
__Scope:__ Contribution to the Functional Servicing Plan, Official Plan Amendment 129. Evaluation of water quality from nutrient and algal biomass concentration of the surface water and from oxygen depletion of the bottom water. Computation of a longterm P budget based on detailed records of runoff and P export from various parts of the watershed. Prediction of P concentrations of epilimnetic, fall turnover and annual averages and of water quality variables for 21 different scenarios, including pre- development, present and post-development, and with and without in-lake restoration techniques.

#### Lake Wilcox, ON, remediation strategy (1994-1995)
__Client:__ Town of Richmond Hill, Ontario, in cooperation with Gartner Lee Lim..  
__Scope:__ Development of a restoration plan for this small urban lake, based on hydrological and nutrient modeling, with special emphasis on the decrease of internal P load.

#### How to update the Water Quality Computer Model of the District of Muskoka, ON (1994)
__Client:__ District Municipality of Muskoka, Ontario.  
__Scope:__ "A Guide and Handbook" that proposes numerous aspects to revise the then current water quality model, based on the phosphorus mass balance approach.

#### Analysis of nutrient dynamics in clear versus brown water lakes (1994)
__Client:__ Department of Fisheries and Oceans, Sault St. Marie, Ontario.  
__Scope:__ Investigation of the phosphorus cycle in clear and brown water lakes.

#### Review of phosphorus dynamics and primary productivity in dystrophic bog lakes (1993)
__Client:__ Department of Fisheries and Oceans, Sault St. Marie, Ontario.  
__Scope:__ Compilation of possible mechanisms that contribute to differences in the productivity of clear and brown water lakes.

#### The importance of internal P load in stratified and polymictic lakes in Alberta (1993)
__Client:__ Ministry of the Environment, Edmonton, Alberta.  
__Scope:__ Consulting on the cause of phosphorus increases during summer in Alberta lakes.

#### Lake Wilcox, ON - evaluation of a phosphorus budget and recommendations to in-lake restoration (1993)
__Client:__ Michael Michalski Associates, Bracebridge, Ontario.  
__Scope:__ Review of a P mass balance of this lake with substantial internal P load and preliminary investigation of remediation possibilities.

#### Heat and pollutant budgets for streams and holding ponds in the Markham area (1993)
__Client:__ Michael Michalski Associates, Bracebridge, Ontario.  
__Scope:__ Modelling of temperature, phosphorus and total suspended solids for a watercourse involving several streams and artificial (stormwater) ponds.

#### Evaluation of the trophic state of Glen Lake, MI (1992)
__Client:__ Glen Lake Association.  
__Scope:__ Evaluation of water quality from nutrient and algal biomass concentration of the surface water and from oxygen depletion of the bottom water with emphasis on sediment release of phosphorus.

#### Continuation of the study of the anoxic factor of lakes and its prediction (1992)
__Client:__ Ontario Ministry of the Environment, Central Region, Toronto.  
__Scope:__ Quantification of hypolimnetic anoxia in lakes of south-central Canada as anoxic factor.

#### A study of the anoxic factor of lakes and its prediction (1990-1991)
__Client:__ Ontario Ministry of the Environment, Central Region, Toronto.  
__Scope:__ Development of a quantitative measure of hypolimnetic anoxia, the anoxic factor.

#### Study of iron cycles in lakes using whole lake mass balances (1989-90)
__Client:__ Ontario Ministry of the Environment, Central Region, Toronto.  
__Scope:__ Development of a mass balance model for iron and the prediction of iron concentrations in lakes.


### 1980-1989 {#y1980}

#### Sediment phosphorus release in core tubes and in-situ (1986-1988)
__University:__ York University, Downsview, Toronto.  
__Granting agency:__ Natural Sciences and Engineering Research Council of Canada.  
__Scope:__ Comparison of the phosphorus release rate from anoxic sediments with different sediment fractions of phosphorus and iron.

#### Consulting on the sediment phosphorus release in Rice and Sturgeon Lakes, ON (1987)
__Client:__ Ontario Ministry of the Environment, Central Region, Toronto.  
__Scope:__ Help developing a workplan to determine P release in these shallow lakes.

#### Phosphorus budget for Gravenhurst Bay of Lake Muskoka, ON (1986)
__Client:__ Ontario Ministry of the Environment, Central Region, Toronto.  
__Scope:__ Predictions of phosphorus, oxygen and chlorophyll concentration averages for different levels of sewage treatment plant effluents, based on P budget modelling.

#### Determination of sediment water interactions in Gravenhurst Bay, ON (experimental) (1985)
__Client:__ Ontario Ministry of the Environment, Central Region, Toronto.  
__Scope:__ Quantification of phosphorus release from the sediment of Gravenhurst Bay of Lake Muskoka and determination of the depth that is involved in sediment release.

#### Evaluation of hypolimnetic withdrawal as a restoration technique for Lake Waramaug, CT (1985)
__Client:__ Lake Waramaug Task Force, Connecticut.  
__Granting Agency:__ Jessie Smith Noyes Foundation.  
__Scope:__ Determination of changes in the water quality of Lake Waramaug and Lake Wononskopomuk, Connecticut, as a consequence of the in-lake restoration technique of hypolimnetic withdrawal.

#### Sediment Phosphorus Speciation (1984-1985)
__University:__ Trent University, Peterborough, ON  
__Granting agency:__ Ontario Ministry of the Environment.  
__Scope:__ Speciation of profundal lake sediment from several south central Ontario lakes with special emphasis on reductant soluble phosphorus and iron fractions.
